DROP TABLE RSAssignedTo;
DROP TABLE CAssignedTo;
DROP TABLE Staff;
DROP TABLE CheckIn;
DROP TABLE Customer;
DROP TABLE Room;
DROP TABLE Hotel;


DROP SEQUENCE staff_seq;
DROP SEQUENCE hotel_seq;
DROP SEQUENCE customer_seq;
DROP SEQUENCE room_seq;